Update build pipeline to include ESLint report and handle ESLint failure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,11 @@ jobs:
         run: mkdir -p eslintReports
       - name: Create ESLint report
         run: npx eslint "src/**/*.{ts,tsx}" --format json --output-file eslintReports/eslint-report.json
+      - name: Create ESLint report
+        run: |
+          npx eslint "src/**/*.{ts,tsx}" --format json --output-file eslintReports/eslint-report.json || (
+            echo "ESLint failed. Outputting error log:" && cat eslintReports/eslint-report.json && exit 1
+          )
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
         env:
